### ISSUE TITLE
Update recast to 

### ISSUE THREAD

**Issue by luchsamapparat** [suchipi/transform-imports#4]
Hi,

could you release a new version with recast updated to 0.17.3? That way it would be possible to pass a TypeScript parser and do transformations on TypeScript files. I tried it locally by overriding the recast version transform-imports uses and it works flawlessly. :)

**Comment by suchipi** [comment]
Sure! I'll try to do that in the next week or so.

**Comment by luchsamapparat** [comment]
![image](https://user-images.githubusercontent.com/875017/55292157-621b0700-53e7-11e9-9d4a-7cc54e060431.png)

**Comment by suchipi** [comment]
Thanks for the reminder! Sorry that I forgot about it. It's now published in version 2.1.0!

**Comment by luchsamapparat** [comment]
No problem, I was in no hurry. Thanks a lot!

**Comment by luchsamapparat** [comment]
btw, that's what I needed it for:
https://www.npmjs.com/package/refactor-imports

thanks again :)
